services:
  app:
    image: beauty-app-project-new-optimize:v2
    container_name: beautyapp
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/beautyproject
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/mysql_root_password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD_FILE: /run/secrets/redis_password
    ports:
      - "8080:8080"
    networks:
      - beautyapp-network
    secrets:
      - mysql_root_password
      - redis_password

  db:
    image: mysql:8.0
    container_name: beautyapp-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: beautyproject
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    ports:
      - "3306:3306"
    volumes:
      - beautyapp-db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - beautyapp-network
    secrets:
      - mysql_root_password

  redis:
    image: pranjalnagarro/beautyappproject:beautyappredis
    container_name: beautyapp-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - beautyapp-redisdata:/data
    command: >
      sh -c "redis-server --requirepass $(cat /run/secrets/redis_password) --appendonly yes"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $(cat /run/secrets/redis_password) ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - beautyapp-network
    secrets:
      - redis_password

  bench:
    image: docker/docker-bench-security:latest
    container_name: docker-bench
    privileged: true
    pid: host
    network_mode: host
    volumes:
      - /var/lib:/var/lib:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/lib/systemd:/usr/lib/systemd:ro
      - /etc:/etc:ro
      - /etc/os-release:/etc/os-release:ro
      - ./bench-reports:/output
    entrypoint: >
      sh -c "./docker-bench-security.sh | tee /output/bench-report-$(date +%F_%H-%M-%S).log"


secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  redis_password:
    file: ./secrets/redis_password.txt

volumes:
  beautyapp-db_data:
  beautyapp-redisdata:

networks:
  beautyapp-network:
    driver: bridge

